training:
  batch_size: 32
  n_epochs: 500000
  n_iters: 80001
  snapshot_freq: 5000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false
  fine_tune_epochs: 5000

sampling:
  batch_size: 16
  data_init: false
  step_lr: 0.0000009
  n_steps_each: 3
  ckpt_id: 80000
  final_only: false
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 8
  save_steps: 300

fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000009
  n_steps_each: 3
  begin_ckpt: 80000
  end_ckpt: 80001
  verbose: false
  ensemble: false

test:
  begin_ckpt: 80000
  end_ckpt: 80000
  batch_size: 100

data:
  dataset: "FFHQ"
  image_size: 256
  channels: 3
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 8
  data_dir: "./exp/datasets/FFHQ/FFHQ.train.npz"

model:
  sigma_begin: 348
  num_classes: 2311
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.001
  
OT:
  gene_source: False
  source_dir: "./exp/image_samples/ffhq/"
  h_name: #"./exp/logs/ffhq/ot/h_6000.pt"
  backSteps: 20
  max_iter: 10000
  lr_ot: 20 #16
  bat_size_sr: 10000
  bat_size_tg: 3500
  topk: 1
  angle_thresh: 0.7
